### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by mrinal18** [Yunski/cos429-capsnet#1]
Hey, i was following your code and there's a problem i was facing.

how do i train another dataset which is of this form

class1/
image1.jpg
image2.jpg

class2/
image1.jpg
image2.jpg

**Comment by Yunski** [comment]
Hi Mrinal18,

My apologies for not noticing this issue. You would have to write your own code for loading batches of images from your dataset. See smallnorb.py for an example of formatting data for use with tensorflow queues, or if you do not want to use queues, see mnist.py for an example of loading batches of images. Unfortunately, I did not write a generic pipeline that can take in any dataset. 
Hope this helps.
